### ISSUE TITLE
Check and merge branch

### ISSUE THREAD

**Issue by stevenhwu** [ComputationalAgronomy/biopathway-prediction#11]
Please have a look and see if there are any branches can be merged into main branch with PR 

or deleted it if it's obsolete

**Comment by yehzx** [comment]
Sure, I'll also upload the code not in the pipeline but for the later analysis and plotting.
Besides, I'm considering creating another repo and after we clean up the code, I'll upload the final version to that repo and make it public for use.

**Comment by stevenhwu** [comment]
Don't create another repo, not sustainable and can't manage it. people just
keep evolving one as they publish and keep updating it.
