### ISSUE TITLE
Update project config

### ISSUE THREAD

**Issue by stevenhwu** [ComputationalAgronomy/biopathway-prediction#15]
1. remove the dependence of git-lfs

2. Double check Python version, >3.10, <3.12
4. Update the package dependence. Guard against the new numpy 2.0 release for now.

5. `pip install .` # remove `-e`

**Comment by yehzx** [comment]
1.  Removed
2.  Tested on python 3.10 - 3.12, both `windows` and `ubuntu`
3.  Change all package dependencies to no less than
4.  Changed and verified

**Comment by stevenhwu** [comment]
ready to close?
