### ISSUE TITLE
Meeting Schedule

### ISSUE THREAD

**Issue by yehzx** [ComputationalAgronomy/biopathway-prediction#2]
### 9/15 Agenda
1. - [x] reference letter
Genome Biology and Systems Degree Program
<http://gsb.lifescience.ntu.edu.tw/enroll_master.htm>
2. - [x] progress report, short discussion of the following steps and the schedule from now to version 1
workflow: NCBI DNA Sequences -> Prodigal -> Blastp -> Enzyme Mapping -> Result -> Visualization
some questions about programming styles (e.g. do it in shell script or python, the best place to save temp files...) 
3. - [x] parallel running of programs
I'll create a new issue to describe what's going on and how the result is different from what I expected

(1: highest priority, not necessary to finish them all)
Not important: Something I wonder: if I create an ec2 instance with appended ssd and create an image, what if I load the template but with an instance not having appended ssd? what will happen?

Todo before early October (9/22, 9/29 two meetings left):
- [x] code review

**Comment by stevenhwu** [comment]
check `nohup`
and `&` running things/job at the background

i.e.

```bash
nohup aws s3 cp SOURCE DEST  &
```

**Comment by yehzx** [comment]
### 10/6 Agenda
1. - [ ] Discuss some of my ideas to analyze the result
See S3 bucket `compagron-results/zye21/meeting/`. To see how the pathway look like, I make a diagram in the folder `src/pathway/`.
2. - [ ] A few things to make my life easier? #7

**Comment by yehzx** [comment]
### 10/13 Agenda
1. - [ ] Review the new commits in #8
I added and revised something after you refactored my code. 
2.  - [ ] Work in progress: refactor module.py
Let's have a look at the branch `refactor_main_and_module` and see if I should keep completing it or modify something before I keep going.
